package com.example.util

object Localization {
    enum class Language(val code: String, val label: String) {
        ENGLISH("en", "English"),
        MARATHI("mr", "मराठी"),
        HINDI("hi", "हिंदी")
    }

    fun get(key: String, lang: String = "en"): String {
        return strings[lang]?.get(key) ?: strings["en"]?.get(key) ?: key
    }

    private val strings: Map<String, Map<String, String>> = mapOf(
        "en" to mapOf(
            "app_name" to "Frenova",
            "tagline" to "Meaningful Friendships & Safe Communities",
            "home" to "Home",
            "discover" to "Discover",
            "create" to "Create",
            "messages" to "Messages",
            "profile" to "Profile",
            "sign_in_google" to "Sign in with Google",
            "welcome_title" to "Connect with Real Friends",
            "welcome_subtitle" to "A wholesome, safe community space — not a dating app. Share thoughts, join live audio/video rooms, and chat freely.",
            "posts" to "Posts",
            "reels" to "Reels",
            "rooms" to "Rooms",
            "friends" to "Friends",
            "friend_requests" to "Friend Requests",
            "add_friend" to "Add Friend",
            "accept" to "Accept",
            "reject" to "Reject",
            "remove_friend" to "Remove Friend",
            "search_hint" to "Search friends, topics or interests...",
            "audio_room" to "Audio Room",
            "video_room" to "Video Room",
            "text_room" to "Text Room",
            "public" to "Public",
            "private" to "Private",
            "join_room" to "Join Room",
            "create_room" to "Create Room",
            "create_post" to "Create Post",
            "create_reel" to "Create Reel",
            "what_on_mind" to "Share something positive with friends...",
            "like" to "Like",
            "comment" to "Comment",
            "share" to "Share",
            "save" to "Save",
            "report" to "Report",
            "block" to "Block",
            "unblock" to "Unblock",
            "report_title" to "Report Content or User",
            "report_reason_spam" to "Spam or Advertising",
            "report_reason_harassment" to "Harassment or Bullying",
            "report_reason_inappropriate" to "Inappropriate or Adult Content",
            "report_reason_dating" to "Dating / Solicitation violation",
            "report_reason_other" to "Other safety concern",
            "submit_report" to "Submit Report",
            "data_saver" to "Data Saver",
            "data_saver_desc" to "Save data & optimize for low-end devices",
            "private_account" to "Private Account",
            "private_account_desc" to "Only accepted friends can see your posts",
            "location_sharing" to "Location Sharing",
            "location_sharing_desc" to "Off by default. Only shows approximate city",
            "language" to "Language",
            "dark_mode" to "Dark Mode",
            "developer_mode" to "Developer Mode",
            "developer_pin_title" to "Developer PIN Verification",
            "developer_pin_desc" to "Enter secure PIN to access Developer Dashboard",
            "verify_pin" to "Verify PIN",
            "dev_dashboard" to "Developer Console",
            "reports_queue" to "Moderation Queue",
            "audit_logs" to "Audit Logs",
            "system_stats" to "Analytics",
            "announcements" to "Announcements",
            "save_changes" to "Save Changes",
            "sign_out" to "Sign Out"
        ),
        "mr" to mapOf(
            "app_name" to "फ्रेनोव्हा (Frenova)",
            "tagline" to "सच्ची मैत्री आणि सुरक्षित समुदाय",
            "home" to "मुख्यपृष्ठ",
            "discover" to "शोधा",
            "create" to "तयार करा",
            "messages" to "संदेश",
            "profile" to "प्रोफाइल",
            "sign_in_google" to "गुगलने साइन इन करा",
            "welcome_title" to "खऱ्या मित्रांशी कनेक्ट व्हा",
            "welcome_subtitle" to "एक सुरक्षित व मैत्रीपूर्ण व्यासपीठ — हे डेटिंग अॅप नाही. विचार शेअर करा, ऑडिओ/व्हिडिओ रूम्समध्ये सामील व्हा.",
            "posts" to "पोस्ट्स",
            "reels" to "रील्स",
            "rooms" to "रूम्स",
            "friends" to "मित्र",
            "friend_requests" to "मित्र विनंत्या",
            "add_friend" to "मित्र बनवा",
            "accept" to "स्वीकारा",
            "reject" to "नाकारा",
            "remove_friend" to "मित्र काढा",
            "search_hint" to "मित्र किंवा विषय शोधा...",
            "audio_room" to "ऑडिओ रूम",
            "video_room" to "व्हिडिओ रूम",
            "text_room" to "टेक्स्ट रूम",
            "public" to "सार्वजनिक",
            "private" to "खाजगी",
            "join_room" to "रूममध्ये जा",
            "create_room" to "रूम तयार करा",
            "create_post" to "पोस्ट तयार करा",
            "create_reel" to "रील तयार करा",
            "what_on_mind" to "मित्रांसोबत काहीतरी चांगले शेअर करा...",
            "like" to "लाईक",
            "comment" to "टिप्पणी",
            "share" to "शेअर",
            "save" to "जतन करा",
            "report" to "तक्रार नोंदवा",
            "block" to "ब्लॉक करा",
            "unblock" to "अनब्लॉक करा",
            "report_title" to "तक्रार नोंदवा",
            "report_reason_spam" to "स्पॅम किंवा जाहिरात",
            "report_reason_harassment" to "त्रास देणे किंवा छळ",
            "report_reason_inappropriate" to "अयोग्य सामग्री",
            "report_reason_dating" to "डेटिंग नियमांचे उल्लंघन",
            "report_reason_other" to "इतर सुरक्षितता समस्या",
            "submit_report" to "तक्रार पाठवा",
            "data_saver" to "डेटा सेव्हर",
            "data_saver_desc" to "कमी डेटा वापरा आणि फोन हलका ठेवा",
            "private_account" to "खाजगी खाते",
            "private_account_desc" to "केवळ स्वीकारलेले मित्र तुमच्या पोस्ट पाहू शकतात",
            "location_sharing" to "स्थान शेअरिंग",
            "location_sharing_desc" to "नेहमी बंद. केवळ अंदाजे शहर दिसते",
            "language" to "भाषा (Language)",
            "dark_mode" to "डार्क मोड",
            "developer_mode" to "डेव्हलपर मोड",
            "developer_pin_title" to "डेव्हलपर पिन पडताळणी",
            "developer_pin_desc" to "डेव्हलपर डॅशबोर्डसाठी पिन प्रविष्ट करा",
            "verify_pin" to "पिन तपासा",
            "dev_dashboard" to "डेव्हलपर कन्सोल",
            "reports_queue" to "तक्रारी निवारण",
            "audit_logs" to "ऑडिट नोंदी",
            "system_stats" to "विश्लेषण",
            "announcements" to "घोषणा",
            "save_changes" to "बदल जतन करा",
            "sign_out" to "साइन आउट"
        ),
        "hi" to mapOf(
            "app_name" to "फ्रेनोवा (Frenova)",
            "tagline" to "सच्ची दोस्ती और सुरक्षित समुदाय",
            "home" to "होम",
            "discover" to "खोजें",
            "create" to "बनाएं",
            "messages" to "संदेश",
            "profile" to "प्रोफाइल",
            "sign_in_google" to "गूगल से साइन इन करें",
            "welcome_title" to "सच्चे दोस्तों से जुड़ें",
            "welcome_subtitle" to "एक सुरक्षित और स्वस्थ समुदाय — यह डेटिंग ऐप नहीं है। विचार साझा करें, ऑडियो/वीडियो रूम में शामिल हों।",
            "posts" to "पोस्ट्स",
            "reels" to "रील्स",
            "rooms" to "रूम्स",
            "friends" to "दोस्त",
            "friend_requests" to "दोस्ती अनुरोध",
            "add_friend" to "दोस्त जोड़ें",
            "accept" to "स्वीकार करें",
            "reject" to "अस्वीकार करें",
            "remove_friend" to "दोस्ती हटाएं",
            "search_hint" to "दोस्त या विषय खोजें...",
            "audio_room" to "ऑडियो रूम",
            "video_room" to "वीडियो रूम",
            "text_room" to "टेक्स्ट रूम",
            "public" to "सार्वजनिक",
            "private" to "निजी",
            "join_room" to "रूम में शामिल हों",
            "create_room" to "रूम बनाएं",
            "create_post" to "पोस्ट बनाएं",
            "create_reel" to "रील बनाएं",
            "what_on_mind" to "दोस्तों के साथ कुछ सकारात्मक साझा करें...",
            "like" to "पसंद करें",
            "comment" to "टिप्पणी",
            "share" to "साझा करें",
            "save" to "सहेजें",
            "report" to "रिपोर्ट करें",
            "block" to "ब्लॉक करें",
            "unblock" to "अनब्लॉक करें",
            "report_title" to "रिपोर्ट दर्ज करें",
            "report_reason_spam" to "स्पैम या विज्ञापन",
            "report_reason_harassment" to "परेशान करना या दुर्व्यवहार",
            "report_reason_inappropriate" to "अनुचित सामग्री",
            "report_reason_dating" to "डेटिंग नियमों का उल्लंघन",
            "report_reason_other" to "अन्य सुरक्षा समस्या",
            "submit_report" to "रिपोर्ट भेजें",
            "data_saver" to "डेटा सेवर",
            "data_saver_desc" to "डेटा बचाएं और कम रैम वाले फोन पर सुचारू चलाएं",
            "private_account" to "प्राइवेट अकाउंट",
            "private_account_desc" to "केवल स्वीकार किए गए दोस्त पोस्ट देख सकते हैं",
            "location_sharing" to "स्थान शेयरिंग",
            "location_sharing_desc" to "डिफ़ॉल्ट रूप से बंद। केवल अनुमानित शहर",
            "language" to "भाषा (Language)",
            "dark_mode" to "डार्क मोड",
            "developer_mode" to "डेवलपर मोड",
            "developer_pin_title" to "डेवलपर पिन सत्यापन",
            "developer_pin_desc" to "डेवलपर कंसोल के लिए पिन दर्ज करें",
            "verify_pin" to "पिन सत्यापित करें",
            "dev_dashboard" to "डेवलपर कंसोल",
            "reports_queue" to "शिकायत निवारण",
            "audit_logs" to "ऑडिट लॉग",
            "system_stats" to "एनालिटिक्स",
            "announcements" to "घोषणाएं",
            "save_changes" to "परिवर्तन सहेजें",
            "sign_out" to "साइन आउट"
        )
    )
}
